# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다.

> **pytorch의 tensor는 숫자 데이터 타입만 지원한다.**

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
      
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [2]:
import torch
import numpy as np

In [ ]:
np.array([1, 2, 3], dtype=np.int8) #"int8" )

In [3]:
print('torch Data types')
print("float", torch.float16, torch.float32, torch.float64, torch.float, torch.double)  #torch.float: float32
print("int:", torch.int8, torch.int16, torch.int32, torch.int64, torch.short, torch.int, torch.long)# 가능
print("uint:", torch.uint8, torch.uint16, torch.uint32, torch.uint64)
print("bool:", torch.bool)

torch Data types
float torch.float16 torch.float32 torch.float64 torch.float32 torch.float64
int: torch.int8 torch.int16 torch.int32 torch.int64 torch.int16 torch.int32 torch.int64
uint: torch.uint8 torch.uint16 torch.uint32 torch.uint64
bool: torch.bool


In [ ]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
# a = torch.tensor([[1,2],[3,4]], dtype=torch.float32, 
#                   device='cuda') # tensor를 GPU 메모리로 올린다.

print("shape:", a.shape, a.size())
print("0축 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)  # type(): Tensor 객체 타입. dtype: data type => 둘은 좀 다르다.
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device)  # tensor를 다루는 processor(메모리위치) - cpu, cuda(gpu)

shape: torch.Size([2, 2]) torch.Size([2, 2])
0축 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [7]:
aa = torch.tensor(range(10), dtype=torch.int8)
print(aa)
aa.type()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)


'torch.CharTensor'

In [8]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32  # torch.tensor([1, 3, 7], dtype=torch.float32)
print(b.dtype)
c = torch.IntTensor([10,20,30])    # int32
print(c.dtype)
d = torch.DoubleTensor([1, 2, 3])  # float64
print(d.dtype)
e = torch.LongTensor([10, 20, 30]) # int64
print(e.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


## 동일한 값을 원소로 가지는 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(size, fill_value), full_like(텐서, fill_value)**: 지정한 값으로 구성된 tensor생성
  - size 
    - shape을 지정한다.
    - zeros, ones는 가변인자이므로 축별 size를 순서대로 서정
    - full 은 tuple/list로 shape을 지정한다.
    

In [13]:
a = torch.zeros(3,2,3) # 3 x 2 x 3
print(a.dtype, a.shape)
a
torch.ones(2,3)  # 2 X 3
torch.full([3,2], fill_value=100) # 3 x 2


torch.float32 torch.Size([3, 2, 3])


tensor([[100, 100],
        [100, 100],
        [100, 100]])

In [16]:
# 특정 배열과 동일한 shape의 tensor 생성.
a = torch.tensor([[1, 2],[3, 4]]) # 2 x 2

print(a.shape)
b = torch.zeros_like(a)  # a와 같은 shape, dtype 으로 생성.
b = torch.ones_like(a)
b = torch.full_like(a, 20)
print(b.shape, b.dtype)
b

torch.Size([2, 2])
torch.Size([2, 2]) torch.int64


tensor([[20, 20],
        [20, 20]])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [20]:
torch.arange(10)  # end. 0 ~ 10-1 1씩 증가
torch.arange(10, 20) # start, end
torch.arange(0, 1, 0.1) # 0 ~ 1-0.1, 0.1 
torch.arange(10, 1, -1) # 10 ~ 1-(-1), -1 

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [22]:
torch.linspace(0, 10, 5) # 0 ~ 10, 5개원소
torch.linspace(0, 1, 11)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [23]:
torch.empty(3,2,7) # 3 X 2 X 7

tensor([[[6.4521e-33, 2.0291e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [ ]:
# torch.manual_seed(0)  # seed 설정
torch.rand(1, 3, 5) # 1 x 3 x 5
torch.randn(30, 3) # 30 X 3  # 표준정규분포
torch.normal(mean=10, std=3, size=(2, 5)) 
# (정규분포) 지정한 평균, 표준편차를 따르는 정규분포 난수
torch.randint(1, 100, (3, 3, 6))  
torch.randperm(100) # 0 ~ 99 를 섞어서 구성

tensor([2, 3, 4, 1, 0])

In [47]:
a = torch.arange(100)
a
# a 섞기
idx = torch.randperm(100) # 0 ~ 99 섞어서 반환. -> index
idx
b = a[idx]

In [48]:
b

tensor([85,  6, 38, 63, 52, 69, 78, 20, 28, 57, 96, 92, 94, 11, 40, 42, 61, 30,
        47, 29, 14, 59, 58, 18, 98, 68, 95, 67, 82, 54, 44, 53, 31, 91,  3, 55,
        46, 17,  9, 73, 27, 43,  4, 49, 64, 50, 71, 34, 72, 88, 56, 41,  0, 22,
        26, 83, 76, 24, 19, 37, 90,  7, 10, 93, 21, 48, 51,  5, 32, 33, 87, 36,
        74, 35, 45,  2, 84, 13, 16, 75,  8, 79, 39, 65,  1, 86, 62, 23, 60, 97,
        80, 99, 89, 15, 70, 81, 12, 77, 66, 25])

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [52]:
import torch
# torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'

device = 'mps' if torch.backends.mps.is_available() else 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'cpu'

In [ ]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device) #생성할 때 device 지정.
print(t, t.device) # tensor가 어느 device에 있는지 확인

tensor([1., 2., 3.]) cpu


In [56]:
t2 = t.to("cpu")  # 다른 device로 옮기기.
print(t2, t2.device)

tensor([1., 2., 3.]) cpu


## tensor를 상수로 변환
- torch.Tensor객체를 파이썬 상수로 변환.
- tensor객체.item()
    - Scalar(상수) 또는 원소가 하나인 tensor를 python 상수로 변환

In [57]:
print(torch.tensor(30))

tensor(30)


In [61]:
a = torch.tensor(10)  # 상수(scalar) => 0차원 Tensor
print(a, a.ndim)
print(a.item())
print(type(a), type(a.item()))

tensor(10) 0
10
<class 'torch.Tensor'> <class 'int'>


In [62]:
b = torch.tensor([[20]]) # 원소가 하나인 N차원 배열
print(b, b.dim())
print(b.item()) #원소가 하나인 배열(텐서) 변환 가능

tensor([[20]]) 2
20


In [64]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [ ]:
d = torch.tensor([10], device='cuda')
print(d)
print(d.item())

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [65]:
import numpy as np
import torch

In [67]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr, dtype=torch.float32)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.to("cpu").numpy()

tensor([[-0.1430,  0.8537, -0.1173],
        [-0.1223, -0.7719, -0.5440],
        [-1.0836,  1.5704, -1.0089]])


array([[-0.14300045,  0.8536578 , -0.11727726],
       [-0.12230916, -0.7719077 , -0.5439859 ],
       [-1.083639  ,  1.5703666 , -1.0088626 ]], dtype=float32)

In [ ]:
t2 = torch.randn(2,2, device="cuda")
t2

In [ ]:
t2.numpy() 
# t2.to("cpu").numpy()

# 원소 조회및 변경 

## indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>**


In [69]:
t = torch.randint(-10, 10, (100, ))
t

tensor([ -3, -10,   2,  -8,   4,  -7,   5,  -4, -10,  -1,   8,  -5,  -9,   2,
          2,  -1,   1,   2,  -3,   4,  -4,  -5,  -1,  -4,   4,   7,   8, -10,
        -10,   9,   5,  -1,  -6,  -5,   9,  -2,   2,  -3,   3,  -3,  -7,   4,
          7,  -1,   4,  -2,   1,   9,   7,   3,  -5,   2, -10,  -3,   0,  -9,
          4,   5,   9,   8,   7,   5,   9,  -9,  -3,  -7,   8, -10,   9,   5,
          4, -10,   2,  -4,  -3,  -1,   8,   0, -10,   8,  -5,   0,   4, -10,
         -1,  -5,  -3,  -6,  -9,   7,   8,  -3,  -6,   7,   5,   2,  -4,   7,
          9, -10])

In [72]:
t[0].item()
t[[1, 5, -1]] # 여러개 조회-> fancy indexing

tensor([-10,  -7, -10])

In [78]:
t[:5] # 0 ~ 4
t[10:15]
t[90:]
t[3:30:3]

####### step 음수 안된다. 그래서 reverse(역순 조회)가 안됨. reverse하려면 flip() 사용
# t[10:1:-2]  
t[1:10:2].flip(dims=(0,)) #reverse

tensor([ -1,  -4,  -7,  -8, -10])

In [79]:
t[1:10:2]

tensor([-10,  -8,  -7,  -4,  -1])

## boolean index
- 논리 연산은 &, |, ~ 을 사용한다.

In [81]:
t > 0

tensor([False, False,  True, False,  True, False,  True, False, False, False,
         True, False, False,  True,  True, False,  True,  True, False,  True,
        False, False, False, False,  True,  True,  True, False, False,  True,
         True, False, False, False,  True, False,  True, False,  True, False,
        False,  True,  True, False,  True, False,  True,  True,  True,  True,
        False,  True, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True, False, False, False,  True, False,  True,  True,
         True, False,  True, False, False, False,  True, False, False,  True,
        False, False,  True, False, False, False, False, False, False,  True,
         True, False, False,  True,  True,  True, False,  True,  True, False])

In [82]:
# boolean index
t[t > 0]

tensor([2, 4, 5, 8, 2, 2, 1, 2, 4, 4, 7, 8, 9, 5, 9, 2, 3, 4, 7, 4, 1, 9, 7, 3,
        2, 4, 5, 9, 8, 7, 5, 9, 8, 9, 5, 4, 2, 8, 8, 4, 7, 8, 7, 5, 2, 7, 9])

In [84]:
t[(t > 0) & (t < 5)]

tensor([2, 4, 2, 2, 1, 2, 4, 4, 2, 3, 4, 4, 1, 3, 2, 4, 4, 2, 4, 2])

In [88]:
# boolean index 처리 함수.
t.masked_select(t > 0)

tensor([2, 4, 5, 8, 2, 2, 1, 2, 4, 4, 7, 8, 9, 5, 9, 2, 3, 4, 7, 4, 1, 9, 7, 3,
        2, 4, 5, 9, 8, 7, 5, 9, 8, 9, 5, 4, 2, 8, 8, 4, 7, 8, 7, 5, 2, 7, 9])

In [87]:
t[t>0]

tensor([2, 4, 5, 8, 2, 2, 1, 2, 4, 4, 7, 8, 9, 5, 9, 2, 3, 4, 7, 4, 1, 9, 7, 3,
        2, 4, 5, 9, 8, 7, 5, 9, 8, 9, 5, 4, 2, 8, 8, 4, 7, 8, 7, 5, 2, 7, 9])

In [89]:
t

tensor([ -3, -10,   2,  -8,   4,  -7,   5,  -4, -10,  -1,   8,  -5,  -9,   2,
          2,  -1,   1,   2,  -3,   4,  -4,  -5,  -1,  -4,   4,   7,   8, -10,
        -10,   9,   5,  -1,  -6,  -5,   9,  -2,   2,  -3,   3,  -3,  -7,   4,
          7,  -1,   4,  -2,   1,   9,   7,   3,  -5,   2, -10,  -3,   0,  -9,
          4,   5,   9,   8,   7,   5,   9,  -9,  -3,  -7,   8, -10,   9,   5,
          4, -10,   2,  -4,  -3,  -1,   8,   0, -10,   8,  -5,   0,   4, -10,
         -1,  -5,  -3,  -6,  -9,   7,   8,  -3,  -6,   7,   5,   2,  -4,   7,
          9, -10])

In [90]:
# 변경
t[0] = 100
t

tensor([100, -10,   2,  -8,   4,  -7,   5,  -4, -10,  -1,   8,  -5,  -9,   2,
          2,  -1,   1,   2,  -3,   4,  -4,  -5,  -1,  -4,   4,   7,   8, -10,
        -10,   9,   5,  -1,  -6,  -5,   9,  -2,   2,  -3,   3,  -3,  -7,   4,
          7,  -1,   4,  -2,   1,   9,   7,   3,  -5,   2, -10,  -3,   0,  -9,
          4,   5,   9,   8,   7,   5,   9,  -9,  -3,  -7,   8, -10,   9,   5,
          4, -10,   2,  -4,  -3,  -1,   8,   0, -10,   8,  -5,   0,   4, -10,
         -1,  -5,  -3,  -6,  -9,   7,   8,  -3,  -6,   7,   5,   2,  -4,   7,
          9, -10])

In [91]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [93]:
# t[ 0축, 1축 ]
# t[1, 2].item()
t[0, 2].item()

3

In [ ]:
t[[1, 0, 2], [2,2,2]]  #(1,2), (0,2)
# t[[첫번째값, 두번째값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

# Reshape

## shape 변경
- 원소의 개수가 변하는 shape으로는 reshape이 안된다.
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > tensor.clone(): tensor를 복제한다.

In [95]:
a = torch.rand(12)
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)
               

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [96]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [97]:
a

tensor([0.1367, 0.6535, 0.8170, 0.0070, 0.1479, 0.8704, 0.6184, 0.4688, 0.5894,
        0.4240, 0.1505, 0.0328])

In [100]:
a5[0, 0] = 12.1
# a2[0, 1] = 15.1

print(a5)

tensor([[1.2100e+01, 1.5100e+01, 8.1699e-01, 7.0421e-03],
        [1.4794e-01, 8.7035e-01, 6.1838e-01, 4.6883e-01],
        [5.8938e-01, 4.2398e-01, 1.5052e-01, 3.2785e-02]])


In [102]:
a7

tensor([[[1.2100e+01, 1.5100e+01],
         [8.1699e-01, 7.0421e-03]],

        [[1.4794e-01, 8.7035e-01],
         [6.1838e-01, 4.6883e-01]],

        [[5.8938e-01, 4.2398e-01],
         [1.5052e-01, 3.2785e-02]]])

In [103]:
a

tensor([1.2100e+01, 1.5100e+01, 8.1699e-01, 7.0421e-03, 1.4794e-01, 8.7035e-01,
        6.1838e-01, 4.6883e-01, 5.8938e-01, 4.2398e-01, 1.5052e-01, 3.2785e-02])

In [104]:
# tensor복사: clone() 메소드
r = a.reshape(3, 4).clone()
r[0,0] = 100.1
print(a)

tensor([1.2100e+01, 1.5100e+01, 8.1699e-01, 7.0421e-03, 1.4794e-01, 8.7035e-01,
        6.1838e-01, 4.6883e-01, 5.8938e-01, 4.2398e-01, 1.5052e-01, 3.2785e-02])


In [105]:
r

tensor([[1.0010e+02, 1.5100e+01, 8.1699e-01, 7.0421e-03],
        [1.4794e-01, 8.7035e-01, 6.1838e-01, 4.6883e-01],
        [5.8938e-01, 4.2398e-01, 1.5052e-01, 3.2785e-02]])

## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)

In [110]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

a1, a2 = a[None, :], a.unsqueeze(dim=0) # dim=정수만가능
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1)   # a[:, None] # 0축 :, 1축 None, 2번축 지정안함 -> 원래대로 그래서 (2, 1, 2) 가됨.
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:, None],  a3.unsqueeze(dim=1)  # unsqueeze(): dim=정수만가능 (한번에 dummy축은 하나만 추가가능.)
print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [ ]:
t = torch.rand(3, 1, 4, 1, 5, 1)
print(t.shape)

r1 = t.squeeze()  #축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 4, 1, 5, 1])
torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5, 1])
torch.Size([3, 4, 5, 1])


# tensor 합치기
- 합치는 기준 축을 제외한 나머지 축의 size는 같아야 한다.
torch.cat([tensorA, tensorB, ...], dim=0) : 기준축 default 는 0

In [3]:
import torch
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3)

In [5]:
torch.cat([a, b], dim=0).shape

torch.Size([4, 5])

In [7]:
torch.cat([a, b, c], dim=0).shape

torch.Size([6, 5])

In [9]:
torch.cat([a, b], axis=1).shape # dim 대신 axis사용가능

torch.Size([2, 10])

In [11]:
torch.cat([a, b, c], axis=1).shape

torch.Size([2, 15])

In [12]:
torch.cat([a, b], axis=-1)  # -1: 마지막 axis

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [15]:
a.shape, d.shape
# 합치는 기준축 이외의 축 size는 같아야 한다.
# torch.cat([a, d])  #dim=0, Error  1축 size가 달라서 Error

(torch.Size([2, 5]), torch.Size([3, 3]))

# 값의 위치(index) 변경
- tensor 원소의 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)` 
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

In [23]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)
print(X)
print("-"* 20)
# y = X.transpose(1, 2)
# print(y.shape)
# print(y)
# print("---------------------------")
z = X.permute(2, 0, 1)
print(z.shape)
print(z)

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
--------------------
torch.Size([4, 2, 3])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])


# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산자 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [25]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c, c.shape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54]) torch.Size([5])


In [26]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [27]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [31]:
a.size(), c.size()

(torch.Size([2, 5]), torch.Size([5]))

In [32]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산함수

### 주요 상수
- torch.e: 자연상수 E
- torch.pi: 원주율

In [34]:
import numpy as np
torch.e, np.e, torch.pi, np.pi

(2.718281828459045, 2.718281828459045, 3.141592653589793, 3.141592653589793)

#### torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [37]:
print(torch.inf > 10000000000000000000, torch.inf < 100000000000000)
print(-torch.inf < -1000000000000000000000, -torch.inf > 10)


True False
True False


In [40]:
print(torch.log(torch.tensor(-1))) # nan (계산결과가 없으므로-없는값-nan 반환)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


## 주요 연산 함수

In [42]:
x=torch.arange(-4, 5).reshape(3,3)
x
print(torch.abs(x))

tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])


In [43]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) # 절대값 
print(torch.sqrt(torch.abs(x))) #  제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x)))
print(torch.log(torch.exp(torch.tensor(1))))  # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)
tensor(1.)


In [48]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=3)) # 소수점 둘째자리 이하에서 반올림
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-4.8563, -2.7426, -3.2307],
        [-0.4834, -0.0784,  2.5634],
        [ 2.2207,  3.7498,  3.8877]])
tensor([[-5., -3., -3.],
        [-0., -0.,  3.],
        [ 2.,  4.,  4.]])
tensor([[-4.8560, -2.7430, -3.2310],
        [-0.4830, -0.0780,  2.5630],
        [ 2.2210,  3.7500,  3.8880]])
tensor([[-5., -3., -4.],
        [-1., -1.,  2.],
        [ 2.,  3.,  3.]])
tensor([[-4., -2., -3.],
        [-0., -0.,  3.],
        [ 3.,  4.,  4.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [ ]:
import torch

In [49]:
x = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])

y = torch.FloatTensor([[1, 2],[1, 2],])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [51]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [52]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# 피연산자로 두개의 3차원 tensor를 axis (1, 2)를 기준으로 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape


torch.Size([3, 4, 5])

## 기술통계함수

In [53]:
X=torch.randn(3,4)
print(X)

tensor([[-1.1586, -1.2206, -1.6431,  0.6906],
        [ 0.5491,  1.5013, -0.1996,  0.7980],
        [ 0.9195, -0.1965, -0.2190,  0.7883]])


In [56]:
print(torch.sum(X))  # default: 전체기준으로 계산. dim=None
print(torch.sum(X, dim=1)) #dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산.
print(torch.sum(X, dim=1, keepdims=True)) # 기술통계함수들을 실행하면 차원이 줄어든다. keepdims=True로 하면 차원유지

tensor(0.6093)
tensor([-3.3318,  2.6487,  1.2923])
tensor([[-3.3318],
        [ 2.6487],
        [ 1.2923]])


In [57]:
print(torch.mean(X))
print(torch.mean(X, dim=0))
print(torch.mean(X, dim=0, keepdims=True))

tensor(0.0508)
tensor([ 0.1033,  0.0281, -0.6873,  0.7590])
tensor([[ 0.1033,  0.0281, -0.6873,  0.7590]])


In [58]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))

tensor(0.9892)
tensor(0.9785)
tensor([1.2287, 1.8900, 0.6853, 0.0035])


In [59]:
# tensor.메소드() 
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[-3.3318],
        [ 2.6487],
        [ 1.2923]])
tensor([[-0.8329],
        [ 0.6622],
        [ 0.3231]])
tensor(0.9892)


In [60]:
X

tensor([[-1.1586, -1.2206, -1.6431,  0.6906],
        [ 0.5491,  1.5013, -0.1996,  0.7980],
        [ 0.9195, -0.1965, -0.2190,  0.7883]])

In [66]:
v = torch.max(X, dim=0)
print("max값:", v.values)
print("max값의 index:", v.indices)

max값: tensor([ 0.9195,  1.5013, -0.1996,  0.7980])
max값의 index: tensor([2, 1, 1, 1])


In [70]:
# print(torch.max(X)) # 전체 기준 max값 계산.
# print(torch.max(X, dim=0))  # 축을 지정하면 return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
# print(torch.max(X, dim=1))
# print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")


print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
print(torch.max(X, dim=1, keepdims=True))

torch.return_types.max(
values=tensor([[ 0.9195,  1.5013, -0.1996,  0.7980]]),
indices=tensor([[2, 1, 1, 1]]))
torch.return_types.max(
values=tensor([[0.6906],
        [1.5013],
        [0.9195]]),
indices=tensor([[3],
        [1],
        [0]]))


In [73]:
print(torch.min(X))
print(torch.min(X, dim=0)) # return_types.min 타입객체로 반환. min값과 min값의 index를 묶어서 반환
print(torch.min(X, dim=1))

tensor(-1.6431)
torch.return_types.min(
values=tensor([-1.1586, -1.2206, -1.6431,  0.6906]),
indices=tensor([0, 0, 0, 0]))
torch.return_types.min(
values=tensor([-1.6431, -0.1996, -0.2190]),
indices=tensor([2, 2, 2]))


In [74]:
print(torch.argmax(X))
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 값의 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 값의 인덱스

tensor(5)
tensor([2, 1, 1, 1])
tensor([3, 1, 0])


In [ ]:
a = torch.max(X, dim=0)
print(a.values)
print(a.indices)

In [ ]:
torch.tensor([1, 2, 3], requires_grad=True)

x = torch.tensor([1, 2, 3])
x.requires_grad = True

# autograd(자동미분)
- 자동 미분을 이용해 gradient(미분계수)를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면(gradient 계산 대상 변수) `requires_grad=True` 로 설정되 있어야 한다. (default: False)

> - **미분**
>   -  (순간) 변화율을 계산한다.
>   - $$\frac{\partial y}{\partial x}$$
>       - x에 대한 y의 변화율. 즉 x가 변하면 y는 얼마나 변할까?

In [75]:
import torch

In [91]:
# gradient를 계산할 tensor는 requires_grad=True 로 설정. (딥러닝모델에서는 parameter들.)
x = torch.tensor([1.0], requires_grad=True)
print(x.requires_grad)
print("변수 x의 data:", x.data)
print("변수 x의 gradient값(미분계산값):", x.grad)

True
변수 x의 data: tensor([1.])
변수 x의 gradient값(미분계산값): None


In [92]:
y = x ** 2  # y는 requires_grad=True인 변수를 이용해서 계산. 
            # 이 계산을 처리하면서 자동으로 도함수도 같이 계산. 그 도함수를 y의 grad_fn에 저장.
            # y.grad_fn = delta y / delata x (dy/dx) = 2 * x
y.data, y.grad_fn

(tensor([1.]), <PowBackward0 at 0x1ba81829330>)

In [93]:
# y.grad_fn(torch.tensor(10))

In [ ]:
# gradient값 계산.(x([1.0])의 변화에 따른 y의 변화율을 계산.)
y.backward() # 계산할 때 사용한 x([1.0])을 이용해 dy/dx 를 계산하고 그 결과를 x.grad에 저장.
# y.grad_fn(x의 값-[1.0]) 계산한 값(gradient값)을 x.grad에 저장.

In [95]:
x.grad

tensor([2.])

In [ ]:
x = torch.tensor([1.0], requires_grad=True) # gradeint를 계산할 대상.
y = x ** 2   # y.grad_fn : 도함수를 저장.
y.backward() # y.grad_fn(x) 계산한 gradient값을 x.grad에 저장
print(x.data, x.grad)
# x = x.data - x.grad * 0.01

tensor([1.]) tensor([2.])


In [101]:
#################
# 두개 변수로 처리
#################
x = torch.tensor([1.0], requires_grad=True)
y = torch.tensor([2.0])
result = x + y  # gradient계산 대상: x. 연산: 덧셈. 뎃셈의 도함수를 result.grad_fn 저장.
# print(result.grad_fn)
result.backward() # x의 gradient를 계산. 그 결과를 x.grad에 저장.
print(x.data, x.grad)

tensor([1.]) tensor([1.])


In [ ]:
x = torch.tensor([1.0], requires_grad=True)
y = torch.tensor([2.0], requires_grad=True)
result = x + 2*y  # gradient 계산 대상: x, y, 연산: 덧셈
# print(result.grad_fn)
result.backward() # result에대해서 x, y의 gradient를 따로 계산(편미분)해서 각각 변수에 저장.
print(x.data, x.grad)
print(y.data, y.grad)

tensor([1.]) tensor([1.])
tensor([2.]) tensor([2.])


In [ ]:
# 합성함수 미분
# 합성함수 - print(int("20")) -> f(g(x))

a = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([2.0], requires_grad=True)

y = a ** 2
z = y + b

print(y.grad_fn, z.grad_fn)
z.backward() # dz/da -> a.grad, dz/db -> b.grad
# dz/d(모든 requires_grad=True 변수)

<PowBackward0 object at 0x000001BA818293F0> <AddBackward0 object at 0x000001BADB65CD60>


In [108]:
a.data, a.grad

(tensor([1.]), tensor([2.]))

In [109]:
b.data, b.grad

(tensor([2.]), tensor([1.]))

## torch.no_grad() 
- no_grad()를 with 구문에서 연산을 할 경우 with block 내에서 requires_grad=True로 설정된 변수를 이용한 계산식이 있더라도 grad_fn을 생성하지 않는다. 즉 gradient를 계산하지 않는다.
- 딥러닝 모델을 평가 하거나 추론을할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [ ]:
a = torch.tensor([3.0], requires_grad=True)
with torch.no_grad():
    z = a ** 2 # 계산 
    print(z.grad_fn)
    print(a.requires_grad)
    # z.backward()

True
tensor([9.], grad_fn=<PowBackward0>)


## gradient 값 초기화
- backward() 에서 계산되어 저장된 gradient값을 초기화한다.
- 반복 학습을 할 경우 gradient가 누적되는 문제가 발생한다. 그래서 한번 학습이 끝나면 다음 학습 전에 초기화하는 작업을 해야 한다.

In [136]:
x = torch.tensor([1.0], requires_grad=True)
print(x.data, x.grad)
y = x ** 2
y.backward()
print(x.data, x.grad)
x.grad = None  # gradient 값 초기화. 하지 않으면 다음 gradient계산 결과를 누적한다.

tensor([1.]) None
tensor([1.]) tensor([2.])


In [137]:
z = x ** 3
z.backward()
print(x.data, x.grad)
x.grad = None

tensor([1.]) tensor([3.])


In [ ]:
k = x ** 4
k.backward()
print(x.data, x.grad)
x.grad = None

tensor([1.]) tensor([4.])
